# Generated by Django 4.0.4 on 2024-04-04 18:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_company_transaction_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFeedingCount',
            fields=[
                ('feed_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('total_count', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.company')),
            ],
        ),
    ]
